export const locations =
    ["TUGHLKABAD", "GK2", "JAIPUR", "OKHLA",
        "PARGATI MAIDAN", "D-30",
        "BHOGAL", "OKHLA",
        "SONIPAT", "HATHRAS",
        "RANJANGAON", "BADARPUR",
        "KASNA", "PRITHLA",
        "BADARPUR", "BADARPUR",
        "KASNA", "FARIDABAD",
        "RAJESH PILOT MARG", "BADARPUR",
        "KASNA", "HATHRAS",
        "DERABASSI", "LADWA",
        "SAHIBABAD", "BHIWANDI",
        "RUDRPUR", "FARIDABAD SEC-16",
        "HALDIRAM", "Badarpur",
        "Prithla", "PANVEL",
        "BHIWADI", "FARIDBAD",
        "DERABASSI", "OKHLA",
        "NOIDA SEC-6 + SAHIBABAD", "FARRUKHNAGAR",
        "Faridabad", "RAJPURA",
        "HAMIDPUR", "FARIDABAD",
        "AIRPORT", "ITO",
        "AIZWAL", "D-30+B-61",
        "BHOGAL", "D-30",
        "BHOGAL", "ITO",
        "AIZWAL", "BADARPUR",
        "KASNA", "KHERA KALAN",
        "BADARPUR",
        "DELHI",
        "MUMBAI",
        "KOLKATA",
        "CHENNAI",
        "BENGALURU",
        "HYDERABAD",
        "PUNE",
        "AHMEDABAD",

        // North India
        "NOIDA",
        "GURUGRAM",
        "FARIDABAD",
        "GHAZIABAD",
        "CHANDIGARH",
        "JAIPUR",
        "AJMER",
        "UDAIPUR",
        "JODHPUR",
        "KOTA",
        "ALWAR",
        "AMBALA",
        "PANIPAT",
        "SONIPAT",
        "KARNAL",
        "ROHTAK",
        "HISAR",
        "LUDHIANA",
        "AMRITSAR",
        "JALANDHAR",
        "PATIALA",
        "DEHRADUN",
        "HARIDWAR",
        "RISHIKESH",
        "SHIMLA",
        "JAMMU",
        "SRINAGAR",

        // West India
        "SURAT",
        "VADODARA",
        "RAJKOT",
        "BHAVNAGAR",
        "JAMNAGAR",
        "GANDHINAGAR",
        "BHIWANDI",
        "THANE",
        "NAVI MUMBAI",
        "KALYAN",
        "ULHASNAGAR",
        "NASHIK",
        "AURANGABAD",
        "NAGPUR",
        "SOLAPUR",
        "KOLHAPUR",
        "SATARA",
        "SANGLI",
        "PANVEL",

        // Central India
        "INDORE",
        "BHOPAL",
        "UJJAIN",
        "GWALIOR",
        "JABALPUR",
        "RAIPUR",
        "BILASPUR",

        // East India
        "PATNA",
        "GAYA",
        "MUZAFFARPUR",
        "RANCHI",
        "JAMSHEDPUR",
        "DHANBAD",
        "KOLKATA",
        "HOWRAH",
        "DURGAPUR",
        "ASANSOL",
        "SILIGURI",
        "BHUBANESWAR",
        "CUTTACK",
        "ROURKELA",

        // South India
        "COIMBATORE",
        "MADURAI",
        "TIRUCHIRAPPALLI",
        "SALEM",
        "ERODE",
        "TIRUPPUR",
        "KOCHI",
        "THIRUVANANTHAPURAM",
        "KOZHIKODE",
        "THRISSUR",
        "PALAKKAD",
        "MYSURU",
        "HUBBALLI",
        "DHARWAD",
        "BELAGAVI",
        "MANGALURU",
        "UDUPI",
        "VIJAYAWADA",
        "GUNTUR",
        "NELLORE",
        "TIRUPATI",
        "VISAKHAPATNAM",
        "KAKINADA",
        "RAJAHMUNDRY",
        "WARANGAL",
        "KARIMNAGAR",

        // North-East
        "GUWAHATI",
        "DIBRUGARH",
        "SILCHAR",
        "IMPHAL",
        "AIZAWL",
        "SHILLONG",
        "AGARTALA",
        "ITANAGAR",
        "KOHIMA",
        "DIMAPUR",

        // UTs & Others
        "PUDUCHERRY",
        "PORT BLAIR",
        "DAMAN",
        "DIU",
        "SILVASSA",
        "LEH",
        "KARGIL",
        "DELHI",
        "NEW DELHI",
        "NORTH DELHI",
        "SOUTH DELHI",
        "EAST DELHI",
        "WEST DELHI",
        "CENTRAL DELHI",
        "DWARKA",
        "ROHINI",
        "JANAKPURI",
        "SHAHDARA",
        "KAROL BAGH",
        "CONNAUGHT PLACE",
        "SAKET",
        "VASANT KUNJ",
        "OKHLA",
        "MAYUR VIHAR",
        "LAXMI NAGAR",
        "NARELA",
        "BAWANA",
        "KIRTI NAGAR",
        "PATPARGANJ",
        "TUGHLAKABAD",
        "BADARPUR",
        "GURUGRAM",
        "FARIDABAD",
        "NOIDA",          // NCR-linked (UP but logistics-wise common)
        "GHAZIABAD",     // NCR-linked
        "SONIPAT",
        "PANIPAT",
        "KARNAL",
        "ROHTAK",
        "JIND",
        "HISAR",
        "BHIWANI",
        "REWARI",
        "MAHENDRAGARH",
        "PALWAL",
        "NUH",
        "YAMUNANAGAR",
        "AMBALA",
        "KURUKSHETRA",
        "KAITHAL",
        "PANCHKULA",
        "CHARKHI DADRI",
        "BAHADURGARH",
        "JHAJJAR",
        "SAFIDON",
        "CHANDIGARH",
        "LUDHIANA",
        "AMRITSAR",
        "JALANDHAR",
        "PATIALA",
        "BATHINDA",
        "MOHALI",
        "KHARAR",
        "ZIRAKPUR",
        "HOSHIARPUR",
        "PATHANKOT",
        "MOGA",
        "FARIDKOT",
        "FATEHGARH SAHIB",
        "RAJPURA",
        "PHAGWARA",
        "KAPURTHALA",
        "SANGRUR",
        "MANSA",
        "FAZILKA",
        "ABOHAR",
        "GURDASPUR",
        "TARN TARAN",
        "LUCKNOW",
        "KANPUR",
        "NOIDA",
        "GREATER NOIDA",
        "GHAZIABAD",
        "MEERUT",
        "HAPUR",
        "BULANDSHAHR",
        "ALIGARH",
        "MATHURA",
        "AGRA",
        "FIROZABAD",
        "ETAWAH",
        "JHANSI",
        "PRAYAGRAJ",
        "VARANASI",
        "MIRZAPUR",
        "SONBHADRA",
        "GORAKHPUR",
        "BASTI",
        "AYODHYA",
        "FAIZABAD",
        "SULTANPUR",
        "AMETHI",
        "RAE BARELI",
        "UNNAO",
        "BAREILLY",
        "SHAHJAHANPUR",
        "MORADABAD",
        "RAMPUR",
        "SAHARANPUR",
        "MUZAFFARNAGAR",
        "SHAMLI",
        "BAGHPAT",
        "PILIBHIT",
        "LAKHIMPUR KHERI",
        "BALLIA",
        "DEORIA",
        "MAU",
        "AZAMGARH",
        "JAUNPUR"



    ];
