export const locations =
    ["TUGHLKABAD", "GK2", "JAIPUR", "OKHLA",
        "PARGATI MAIDAN", "D-30",
        "BHOGAL", "OKHLA",
        "SONIPAT", "HATHRAS",
        "RANJANGAON", "BADARPUR",
        "KASNA", "PRITHLA",
        "BADARPUR", "BADARPUR",
        "KASNA", "FARIDABAD",
        "RAJESH PILOT MARG", "BADARPUR",
        "KASNA", "HATHRAS",
        "DERABASSI", "LADWA",
        "SAHIBABAD", "BHIWANDI",
        "RUDRPUR", "FARIDABAD SEC-16",
        "HALDIRAM", "Badarpur",
        "Prithla", "PANVEL",
        "BHIWADI", "FARIDBAD",
        "DERABASSI", "OKHLA",
        "NOIDA SEC-6 + SAHIBABAD", "FARRUKHNAGAR",
        "Faridabad", "RAJPURA",
        "HAMIDPUR", "FARIDABAD",
        "AIRPORT", "ITO",
        "AIZWAL", "D-30+B-61",
        "BHOGAL", "D-30",
        "BHOGAL", "ITO",
        "AIZWAL", "BADARPUR",
        "KASNA", "KHERA KALAN",
        "BADARPUR",
        "DELHI",
        "MUMBAI",
        "KOLKATA",
        "CHENNAI",
        "BENGALURU",
        "HYDERABAD",
        "PUNE",
        "AHMEDABAD",
        // North India
        "NOIDA",
        "GURUGRAM",
        "FARIDABAD",
        "GHAZIABAD",
        "CHANDIGARH",
        "JAIPUR",
        "AJMER",
        "UDAIPUR",
        "JODHPUR",
        "KOTA",
        "ALWAR",
        "AMBALA",
        "PANIPAT",
        "SONIPAT",
        "KARNAL",
        "ROHTAK",
        "HISAR",
        "LUDHIANA",
        "AMRITSAR",
        "JALANDHAR",
        "PATIALA",
        "DEHRADUN",
        "HARIDWAR",
        "RISHIKESH",
        "SHIMLA",
        "JAMMU",
        "SRINAGAR",
        // West India
        "SURAT",
        "VADODARA",
        "RAJKOT",
        "BHAVNAGAR",
        "JAMNAGAR",
        "GANDHINAGAR",
        "BHIWANDI",
        "THANE",
        "NAVI MUMBAI",
        "KALYAN",
        "ULHASNAGAR",
        "NASHIK",
        "AURANGABAD",
        "NAGPUR",
        "SOLAPUR",
        "KOLHAPUR",
        "SATARA",
        "SANGLI",
        "PANVEL",
        // Central India
        "INDORE",
        "BHOPAL",
        "UJJAIN",
        "GWALIOR",
        "JABALPUR",
        "RAIPUR",
        "BILASPUR",
        // East India
        "PATNA",
        "GAYA",
        "MUZAFFARPUR",
        "RANCHI",
        "JAMSHEDPUR",
        "DHANBAD",
        "HOWRAH",
        "DURGAPUR",
        "ASANSOL",
        "SILIGURI",
        "BHUBANESWAR",
        "CUTTACK",
        "ROURKELA",
        // South India
        "COIMBATORE",
        "MADURAI",
        "TIRUCHIRAPPALLI",
        "SALEM",
        "ERODE",
        "TIRUPPUR",
        "KOCHI",
        "THIRUVANANTHAPURAM",
        "KOZHIKODE",
        "THRISSUR",
        "PALAKKAD",
        "MYSURU",
        "HUBBALLI",
        "DHARWAD",
        "BELAGAVI",
        "MANGALURU",
        "UDUPI",
        "VIJAYAWADA",
        "GUNTUR",
        "NELLORE",
        "TIRUPATI",
        "VISAKHAPATNAM",
        "KAKINADA",
        "RAJAHMUNDRY",
        "WARANGAL",
        "KARIMNAGAR",
        // North-East
        "GUWAHATI",
        "DIBRUGARH",
        "SILCHAR",
        "IMPHAL",
        "AIZAWL",
        "SHILLONG",
        "AGARTALA",
        "ITANAGAR",
        "KOHIMA",
        "DIMAPUR",
        // UTs & Others
        "PUDUCHERRY",
        "PORT BLAIR",
        "DAMAN",
        "DIU",
        "SILVASSA",
        "LEH",
        "KARGIL",
        "NEW DELHI",
        "NORTH DELHI",
        "SOUTH DELHI",
        "EAST DELHI",
        "WEST DELHI",
        "CENTRAL DELHI",
        "DWARKA",
        "ROHINI",
        "JANAKPURI",
        "SHAHDARA",
        "KAROL BAGH",
        "CONNAUGHT PLACE",
        "SAKET",
        "VASANT KUNJ",
        "OKHLA",
        "MAYUR VIHAR",
        "LAXMI NAGAR",
        "NARELA",
        "BAWANA",
        "KIRTI NAGAR",
        "PATPARGANJ",
        "TUGHLAKABAD",
        "NOIDA",          // NCR-linked (UP but logistics-wise common)
        "GHAZIABAD",     // NCR-linked
        "JIND",
        "BHIWANI",
        "REWARI",
        "MAHENDRAGARH",
        "PALWAL",
        "NUH",
        "YAMUNANAGAR",
        "KURUKSHETRA",
        "KAITHAL",
        "PANCHKULA",
        "CHARKHI DADRI",
        "BAHADURGARH",
        "JHAJJAR",
        "SAFIDON",
        "BATHINDA",
        "MOHALI",
        "KHARAR",
        "ZIRAKPUR",
        "HOSHIARPUR",
        "PATHANKOT",
        "MOGA",
        "FARIDKOT",
        "FATEHGARH SAHIB",
        "RAJPURA",
        "PHAGWARA",
        "KAPURTHALA",
        "SANGRUR",
        "MANSA",
        "FAZILKA",
        "ABOHAR",
        "GURDASPUR",
        "TARN TARAN",
        "LUCKNOW",
        "KANPUR",
        "GREATER NOIDA",
        "MEERUT",
        "HAPUR",
        "BULANDSHAHR",
        "ALIGARH",
        "MATHURA",
        "AGRA",
        "FIROZABAD",
        "ETAWAH",
        "JHANSI",
        "PRAYAGRAJ",
        "VARANASI",
        "MIRZAPUR",
        "SONBHADRA",
        "GORAKHPUR",
        "BASTI",
        "AYODHYA",
        "FAIZABAD",
        "SULTANPUR",
        "AMETHI",
        "RAE BARELI",
        "UNNAO",
        "BAREILLY",
        "SHAHJAHANPUR",
        "MORADABAD",
        "RAMPUR",
        "SAHARANPUR",
        "MUZAFFARNAGAR",
        "SHAMLI",
        "BAGHPAT",
        "PILIBHIT",
        "LAKHIMPUR KHERI",
        "BALLIA",
        "DEORIA",
        "MAU",
        "AZAMGARH",
        "JAUNPUR",
        "KASNA",
        "BANGALORE",
        "SURAJPUR BAJAJ",
        "B-61",
        "CHANKYPURI",
        "NOIDA SEC-65",
        "AIRPORT",
        "WASHING LINE",
        "GURUGRAM SEC-37",
        "OKHLA PHASE-I",
        "OKHLA PHASE-II",
        "RANHOLA",
        "BADARPUR + PRITHLA",
        "PRITHLA",
        "MUNDKA + BAWANA",
        "surajpur gr. noida",
        "D-30",
        "BHOGAL",
        "kamla market",
        "c-43 V-trans + VRL",
        "PITHMPUR",
        "HATHRAS",
        "FARIDABAD SEC-24",
        "NIZAMUDDIN",
        "DHURI+BARNALA",
        "NOIDA SEC-63",
        "FARRUKHNAGAR",
        "KHIRKI DULA",
        "LAL KUAN",
        "GR. NOIDA",
        "GHITORNI",
        "DEHRADUN UP/DN",
        "KESHWANA",
        "DADRI",
        "D-28",
        "FULL DAY HOLD",
        "BADARPUR + PRITHLA- 5MT",
        "FARIDABAD HOLD",
        "MOTI BAGH",
        "pargati maidan",
        "okhla",
        "W-8 FULL NIGHT",
        "LAHORI GATE -1PM UNLOAD",
        "khera kalan",
        "badarpur",
        "CHATTARPUR",
        "JAIPUR 15/1 RETURN",
        "AUCHANDI",
        "faridabad sec-24",
        "washing line",
        "NEEMRANA",
        "FARIDABAD SEC-24+59",
        "CHATTRPUR",
        "JAIPUR UP/ DN-15/01 RETURN",
        "1 MURTI GR. NOIDA",
        "TUGHLKABAD",
        "G. K.-2",
        "PARGATI MAIDAN",
        "RANJANGAON",
        "jor bagh+ ghitorni",
        "RAJESH PILOT MARG",
        "ballbhgarh",
        "papatganj 10/1 unload 1 pm",
        "NOIDA SEC-6",
        "BADLI",
        "PALI",
        "NOIDA SEC-67",
        "r k puram",
        "SIRHIND",
        "CHANDNI CHOWK",
        "bangalore",
        "BADARPUR bolero",
        "bazpur",
        "KATHUA",
        "neemrana",
        "GURUGRAM SEC-71",
        "OKHLA + GHITORNI",
        "REWA + INDORE",
        "VIP GATE",
        "hosiery complex noida",
        "MAULI",
        "jagraon",
        "kundli+rai+sonipat",
        "lalru",
        "libaspur",
        "DERABASSI",
        "LADWA",
        "SAHIBABAD",
        "RUDRPUR",
        "FARIDABAD SEC-16",
        "HALDIRAM",
        "Badarpur",
        "Prithla",
        "BHIWADI",
        "FARIDBAD",
        "NOIDA SEC-6 + SAHIBABAD",
        "Faridabad",
        "HAMIDPUR",
        "ITO",
        "AIZWAL",
        "D-30+B-61",
        "KHERA KALAN",
        "DEWAS",
        "OKHLA NSIC",
        "Sirspur",
        "NOIDA SEC-6 + SURAJPUR + KASNA",
        "ICD TKD",
        "PRATAPGARH",
        "GURUGRAM SEC-44",
        "GHAZIPUR",
        "LONI",
        "MUNDKA",
        "TAJ PLACE DHULAKUAN",
        "OKHLA PHASE-II + DELHIVERY",
        "ALIPUR",
        "DELHIVERY",
        "LAHORI GATE",
        "DAHEJ",
        "NSIC OKHLA",
        "SANJAYGANDHI- 2 POINT + ALIPUR + KUNDLI + SONIPAT",
        "GORAKHPUR UP/DN",
        "GURUGRAM SEC-64",
        "W-8",
        "RAI SONIPAT",
        "BAGRU",
        "BALLBHGARH",
        "BIJWASAN",
        "BARNALA",
        "VAPI",
        "JAIPUR + BAWAL",
        "NOIDA SEC - 6 + MEERUT- 3 POINT",
        "BAGDOLA DWARKA",
        "FULL DAY HOLD EMPTY RETURN",
        "NOIDA SEC-6 + 81+80 -2 POINT",
        "JUNGPURA",
        "DASNA",
        "TRILOKPURI UP/DN",
        "KALANDI KUNJ",
        "TOLL",
        "ALIPUR + MANGOLPURI",
        "SONIPAT + BAWANA",
        "KASHIPUR",
        "KAMLA MARKET + SANJAYGANDHI + RAI",
        "SIRSPUR",
        "JIO WORLD CENTRE MUMBAI",
        "MOHAN CO.",
        "SAMALKA",
        "PONTA SAHIB - 2 POINT",
        "EMPTY RETURN",
        "ICD DADRI",
        "LAHORI GATE -2PM UNLOAD",
        "HOLD",
        "BIHTA",
        "MANDI GOVINDGARH",
        "MAYAPURI",
        "PARHLADPUR",
        "SURAJPUR GR. NOIDA",
        "KOTLA",
        "NOIDA PHASE-2",
        "SAMLKHA",
        "NEB SARAI",
        "B-87 OKHLA",
        "TIGAON",
        "KUNDLI",
        "LUHARI",
        "W-13",
        "JOR BAGH",
        "BAHADURGARH + NEEMRANA",
        "V TRANS",
        "BEHROR",
        "GREATER NOIDA + KASNA",
        "121 NO.",
        "BOMBAY",
        "AIIMS",
        "MUNDKA + AUCHANDI"
    ];